services:
  client-prod:
    image: client-prod
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    networks:
      - app-network-prod
    profiles: ["prod"]
  
  client-dev:
    image: client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "80:80"
    networks:
      - app-network-dev
    profiles: ["dev"]

  client-test:
    image: client-test
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
    ports:
      - "80:80"
    networks:
      - app-network-test
    profiles: ["test"]

  server-prod:
    image: server-prod
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL_PROD}
    depends_on:
      - db-prod
    profiles: ["prod"]
    networks:
      - app-network-prod
  
  server-dev:
    image: server-dev
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL_DEV}
    depends_on:
      - db-dev
    profiles: ["dev"]
    networks:
      - app-network-dev
  
  server-test:
    image: server-test
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db-test:5432/postgres-test
    depends_on:
      - db-test
    profiles: ["test"]
    networks:
      - app-network-test
  
  db-prod:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_PROD}
    profiles: ["prod"]
  
  db-dev:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_DEV}
    profiles: ["dev"]
  
  db-test:
    image: postgres:14
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    profiles: ["test"]
  
networks:
  app-network-prod:
    driver: bridge
  app-network-dev:
    driver: bridge
  app-network-test:
    driver: bridge