services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV = production
    ports:
      - "3000:3000"
  
  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
  
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    