basePath: /api/v1
definitions:
  errors.ErrorCode:
    enum:
    - invalid_email
    - failed_hash
    - email_already_exists
    - database_error
    - user_not_found
    - invalid_credentials
    - invalid_token
    - jwt_error
    - external_api_error
    - empty_image_url
    - malformed_url
    - invalid_image_extension
    - invalid_protocol
    - image_already_liked
    - image_not_liked
    type: string
    x-enum-varnames:
    - InvalidEmail
    - FailedHash
    - EmailAlreadyExists
    - DatabaseError
    - UserNotFound
    - InvalidCredentials
    - InvalidToken
    - JWTError
    - ExternalAPIError
    - EmptyImageURL
    - MalformedURL
    - InvalidImageExtension
    - InvalidProtocol
    - ImageAlreadyLiked
    - ImageNotLiked
  models.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  models.CreateUserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      updated_at:
        type: string
    type: object
  models.GetLikedImagesResponse:
    properties:
      images:
        items:
          type: string
        type: array
    type: object
  models.LikeImageRequestBody:
    properties:
      imageURL:
        type: string
    required:
    - imageURL
    type: object
  models.LikeImageResponse:
    properties:
      images:
        items:
          type: string
        type: array
      success:
        type: boolean
    type: object
  models.LoginUserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  models.LoginUserResponse:
    properties:
      id:
        type: string
      token:
        type: string
    type: object
  models.UnlikeImageRequestBody:
    properties:
      imageURL:
        type: string
    required:
    - imageURL
    type: object
  models.UnlikeImageResponse:
    properties:
      image:
        type: string
      success:
        type: boolean
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      passwordHash:
        type: string
      updatedAt:
        type: string
    type: object
  utils.ErrorResponse:
    properties:
      code:
        $ref: '#/definitions/errors.ErrorCode'
      detail:
        description: Optional field for detailed error messages
        type: string
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for WTI-Tech-Interview
  title: WTI-Tech-Interview API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Logs in an existing user with the provided email and password.
      parameters:
      - description: User login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Logs in an existing user.
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registers a new user with the provided email and password.
      parameters:
      - description: User registration request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CreateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Registers a new user.
      tags:
      - auth
  /auth/verify:
    get:
      consumes:
      - application/json
      description: Verifies that the user is authenticated.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Verifies user authentication.
      tags:
      - auth
  /dog/random:
    get:
      consumes:
      - application/json
      description: Returns a random dog image URL from the Dog API.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Returns a random dog image URL.
      tags:
      - dog
  /health:
    get:
      description: Verifies that the server is running and healthy.
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Checks the health of the server.
      tags:
      - health
  /liked_images/{id}:
    delete:
      consumes:
      - application/json
      description: Unlikes an image for the user.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Image URL
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UnlikeImageRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UnlikeImageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Unlikes an image.
      tags:
      - liked_images
    get:
      consumes:
      - application/json
      description: Returns a list of liked images for the user.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetLikedImagesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Returns a list of liked images.
      tags:
      - liked_images
    post:
      consumes:
      - application/json
      description: Likes an image for the user.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Image URL
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LikeImageRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.LikeImageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Likes an image.
      tags:
      - liked_images
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves a user by their ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Retrieves a user by ID.
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
